# Generated by Django 5.0.7 on 2024-07-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("location", models.TextField(max_length=250)),
                ("items", models.TextField(max_length=500)),
                ("lan_lon", models.FloatField(max_length=50)),
                ("full_details", models.TextField(max_length=500)),
            ],
        ),
    ]
