# Generated by Django 5.0.7 on 2024-07-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="full_details",
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="items",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="lan_lon",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="location",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
